istio:
  namespace:
    default: istio-system
    ingress: ${istio.namespace.default}
gateways:
  external: ${istio.namespace.ingress}/mygateway
  test: ${istio.namespace.ingress}/testgateway
identity:
  supports-managed-id: false
  tenant-id: 54947238-c4b1-4ce0-9ec3-11ceaa36ed8b
